name: Code Quality & Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install linting and security tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort bandit safety
    
    - name: Lint with flake8
      run: |
        # Prüfe auf Python-Syntax-Fehler und undefinierte Namen
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Alle anderen Warnungen als nicht-kritisch behandeln
        flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff app/
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff app/
    
    - name: Run security scan with bandit
      run: |
        bandit -r app/ || echo "Bandit hat potentielle Sicherheitsprobleme gefunden - siehe Ausgabe oben"
      continue-on-error: true
    
    - name: Check for known vulnerabilities with safety
      run: |
        safety check || echo "Safety check abgeschlossen"
      continue-on-error: true 